# -*- coding: utf-8 -*-
"""pomodoro_timer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hf44hUYqiY3gywFySO70OSwuB1uIPfA9
"""

# pomodoro timer app ------>  25 minutes work → ☕ 5 minutes break → Repeat After 4 sessions → take a longer break (e.g., 15 minutes)
import datetime , time
from datetime import datetime , timedelta

while True:
  n = input("Enter the number of task that you want to perform or enter (stop/exit) to stop the program:- ")
  if n == 'stop' or n == 'exit':
    break
  else:
    # create a list of dictionaries for each task
    tasks = []
    for i in range(int(n)):
      task_name = input("Enter task name:- ")
      try:
        task_duration = float(input("Enter the time (in minutes):- "))
        break_time = float(input("Enter the break time that you want to take(in minutes):- "))
      except ValueError:
        print("Invalid input. Please enter a valid number.")
        continue

      task={
          'name':task_name,
          'duration':task_duration,
          'break':break_time
      }

      # append each task into list of dictionaries
      tasks.append(task)

    for index, task in enumerate(tasks):
      current_time = datetime.now()
      time_after_work = current_time + timedelta(minutes = task['duration'])
      print(f"\n\nTask to be done {index+1}: {task['name']}")
      print(f"Time when task has been started: {current_time.strftime('%H:%M:%S')}")
      print(f"Time when task has to be completed: {time_after_work.strftime('%H:%M:%S')}\n\n")
      time.sleep(task['duration']*60)

      if (index + 1) % 4 == 0:
        print("\nTime for a long break! (15 mins)\n\n")
        time.sleep(15 * 60)
      else:
        print(f"\nTask has been completed take a {task['break']} min break\n\n")
        time.sleep(task['break']*60)

      print("\nBreak complete!\n")

    print("\nAll tasks completed! For this session\n")